// ============================================================================
//   Ver  :| Author					:| Mod. Date :| Changes Made:
//   V1.1 :| Alexandra Du			:| 06/01/2016:| Added Verilog file
// ============================================================================


//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

`define ENABLE_ADC_CLOCK
`define ENABLE_CLOCK1
`define ENABLE_CLOCK2
`define ENABLE_SDRAM
`define ENABLE_HEX0
`define ENABLE_HEX1
`define ENABLE_HEX2
`define ENABLE_HEX3
`define ENABLE_HEX4
`define ENABLE_HEX5
`define ENABLE_KEY
`define ENABLE_LED
`define ENABLE_SW
`define ENABLE_VGA
`define ENABLE_ACCELEROMETER
`define ENABLE_ARDUINO
`define ENABLE_GPIO

module DE10_LITE_Golden_Top(

	//////////// ADC CLOCK: 3.3-V LVTTL //////////
`ifdef ENABLE_ADC_CLOCK
	input 		          		ADC_CLK_10,
`endif
	//////////// CLOCK 1: 3.3-V LVTTL //////////
`ifdef ENABLE_CLOCK1
	input 		          		MAX10_CLK1_50,
`endif
	//////////// CLOCK 2: 3.3-V LVTTL //////////
`ifdef ENABLE_CLOCK2
	input 		          		MAX10_CLK2_50,
`endif

	//////////// SDRAM: 3.3-V LVTTL //////////
`ifdef ENABLE_SDRAM
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N,
`endif

	//////////// SEG7: 3.3-V LVTTL //////////
`ifdef ENABLE_HEX0
	output		     [7:0]		HEX0,
`endif
`ifdef ENABLE_HEX1
	output		     [7:0]		HEX1,
`endif
`ifdef ENABLE_HEX2
	output		     [7:0]		HEX2,
`endif
`ifdef ENABLE_HEX3
	output		     [7:0]		HEX3,
`endif
`ifdef ENABLE_HEX4
	output		     [7:0]		HEX4,
`endif
`ifdef ENABLE_HEX5
	output		     [7:0]		HEX5,
`endif

	//////////// KEY: 3.3 V SCHMITT TRIGGER //////////
`ifdef ENABLE_KEY
	input 		     [1:0]		KEY,
`endif

	//////////// LED: 3.3-V LVTTL //////////
`ifdef ENABLE_LED
	output		     [9:0]		LEDR,
`endif

	//////////// SW: 3.3-V LVTTL //////////
`ifdef ENABLE_SW
	input 		     [9:0]		SW,
`endif

	//////////// VGA: 3.3-V LVTTL //////////
`ifdef ENABLE_VGA
	output		     [3:0]		VGA_B,
	output		     [3:0]		VGA_G,
	output		          		VGA_HS,
	output		     [3:0]		VGA_R,
	output		          		VGA_VS,
`endif

	//////////// Accelerometer: 3.3-V LVTTL //////////
`ifdef ENABLE_ACCELEROMETER
	output		          		GSENSOR_CS_N,
	input 		     [2:1]		GSENSOR_INT,
	output		          		GSENSOR_SCLK,
	inout 		          		GSENSOR_SDI,
	inout 		          		GSENSOR_SDO,
`endif

	//////////// Arduino: 3.3-V LVTTL //////////
`ifdef ENABLE_ARDUINO
	inout 		    [15:0]		ARDUINO_IO,
	inout 		          		ARDUINO_RESET_N,
`endif

	//////////// GPIO, GPIO connect to GPIO Default: 3.3-V LVTTL //////////
`ifdef ENABLE_GPIO
	inout 		    [35:0]		GPIO
`endif
);



	// ========================================================================
    // PIPELINE PROCESSOR LOGIC
    // ========================================================================
    wire [1:0] ForwardA_E, ForwardB_E;
	wire [31:0] SrcA_Forwarded;
    wire [31:0] SrcB_Forwarded;
	wire StallF, StallD, FlushD, FlushE;
    // --- FETCH STAGE (_F) WIRES ---
    wire [31:0] PC_F, PCNext_F, PCPlus4_F;
    wire [31:0] Instr_F;

    // --- DECODE STAGE (_D) WIRES ---
    wire [31:0] Instr_D, PC_D, PCPlus4_D;
    wire [31:0] RD1_D, RD2_D, ImmExt_D;
    wire [4:0]  Rd_D;
    wire [1:0]  ImmSrc_D; 
    // Control Signals (_D)
    wire       RegWrite_D, MemWrite_D, Jump_D, Branch_D, ALUSrc_D;
    wire [1:0] ResultSrc_D;
    wire [2:0] ALUControl_D;

    // --- EXECUTE STAGE (_E) WIRES ---
    wire [31:0] RD1_E, RD2_E, PC_E, ImmExt_E, PCPlus4_E;
    wire [4:0]  Rd_E, Rs1_E, Rs2_E;
    wire [31:0] SrcA_E, SrcB_E; 
    wire [31:0] ALUResult_E, WriteData_E;
    wire [31:0] PCTarget_E;
    // Control Signals (_E)
    wire       RegWrite_E, MemWrite_E, Jump_E, Branch_E, ALUSrc_E;
    wire [1:0] ResultSrc_E;
    wire [2:0] ALUControl_E;
    wire       Zero_E, PCSrc_E; 

    // --- MEMORY STAGE (_M) WIRES ---
    wire [31:0] ALUResult_M, WriteData_M, PCPlus4_M;
    wire [31:0] ReadData_M;
    wire [4:0]  Rd_M;
    // Control Signals (_M)
    wire       RegWrite_M, MemWrite_M;
    wire [1:0] ResultSrc_M;

    // --- WRITEBACK STAGE (_W) WIRES ---
    wire [31:0] ALUResult_W, ReadData_W, PCPlus4_W, Result_W;
    wire [4:0]  Rd_W;
    // Control Signals (_W)
    wire       RegWrite_W;
    wire [1:0] ResultSrc_W;
	wire cpu_clk;
	assign cpu_clk = KEY[1];
//	assign cpu_clk = MAX10_CLK1_50;
	
	HazardUnit u_hazard (
		.Rs1_E(Rs1_E), 			 .Rs2_E(Rs2_E),
		.Rd_M(Rd_M),             .Rd_W(Rd_W),
		.RegWrite_M(RegWrite_M), .RegWrite_W(RegWrite_W),
		
		.ForwardA_E(ForwardA_E), .ForwardB_E(ForwardB_E)
	);
	
    // ========================================================================
    // 1. FETCH STAGE
    // ========================================================================
    
    // PC Mux (Decides Next PC)
    Mux2 u_pc_mux (
        .d0(PCPlus4_F),  // Normal Next PC
        .d1(PCTarget_E), // Branch Target (from Execute)
        .s(PCSrc_E),     // Branch Decision (from Execute)
        .y(PCNext_F)     // To PC Next input
    );

    ProgramCounter u_pc (
        .clk(cpu_clk),
        .rst_n(KEY[0]),
		.en(~StallF),
        .PCNext(PCNext_F),
        .PC(PC_F)
    );

    // FIXED: Must use PC_F (Output of Register), not PCNext_F
    InstructionMemory u_imem (
        .A(PC_F),
        .RD(Instr_F)
    );

    // FIXED: Must use PC_F
    PCAdder u_pc_adder (
        .PC(PC_F),
        .PCPlus4(PCPlus4_F)
    );

    // --- IF/ID PIPELINE REGISTER ---
    Pipe_IF_ID u_reg_if_id (
        .clk(cpu_clk),
        .rst_n(KEY[0]),
        .en(~StallD),
		.clr(FlushD),
        // Inputs (From Fetch)
        .PC_F(PC_F),
        .Instr_F(Instr_F),
        .PCPlus4_F(PCPlus4_F),
        
        // Outputs (To Decode)
        .PC_D(PC_D),
        .Instr_D(Instr_D),
        .PCPlus4_D(PCPlus4_D)
    );


    // ========================================================================
    // 2. DECODE STAGE
    // ========================================================================

    ControlUnit u_control (
        .Opcode(Instr_D[6:0]),
        .Funct3(Instr_D[14:12]),
        .Funct7b5(Instr_D[30]),
		.Funct7b0(Instr_D[25]),
        .Zero(1'b0),        // Not used in Decode
        .PCSrc(),           // Not used in Decode
        .ResultSrc(ResultSrc_D),
        .MemWrite(MemWrite_D),
        .ALUSrc(ALUSrc_D),
        .ImmSrc(ImmSrc_D), 
        .RegWrite(RegWrite_D),
        .ALUControl(ALUControl_D),
        .Jump(Jump_D),
        .Branch(Branch_D)
    );
	
	HazardDetectionUnit u_hazard_detect (
        .Rs1_D(Rs1_D),
        .Rs2_D(Rs2_D),
        .Rd_E(Rd_E),
        .ResultSrc_E(ResultSrc_E),
        .PCSrc_E(PCSrc_E),
        
        .StallF(StallF),
        .StallD(StallD),
        .FlushD(FlushD),
        .FlushE(FlushE)
    );
    
    // Extract Destination Register (Rd)
    assign Rd_D = Instr_D[11:7];

    RegisterFile u_reg_file (
        .clk(cpu_clk),
        // Writeback Port (Inputs from Stage W)
        .WE3(RegWrite_W),
        .A3(Rd_W),
        .WD3(Result_W),
        // Read Ports (Inputs from Stage D)
        .A1(Instr_D[19:15]),
        .A2(Instr_D[24:20]),
        .RD1(RD1_D),
        .RD2(RD2_D)
    );

    Extend u_extend (
        .Instr(Instr_D[31:7]),
        .ImmSrc(ImmSrc_D),
        .ImmExt(ImmExt_D)
    );

    // --- ID/EX PIPELINE REGISTER ---
    Pipe_ID_EX u_reg_id_ex (
        .clk(cpu_clk),
        .rst_n(KEY[0]),
        .clr(FlushE),
        // Control
        .RegWrite_D(RegWrite_D),     .RegWrite_E(RegWrite_E),
        .ResultSrc_D(ResultSrc_D),   .ResultSrc_E(ResultSrc_E),
        .MemWrite_D(MemWrite_D),     .MemWrite_E(MemWrite_E),
        .Jump_D(Jump_D),             .Jump_E(Jump_E),
        .Branch_D(Branch_D),         .Branch_E(Branch_E),
        .ALUControl_D(ALUControl_D), .ALUControl_E(ALUControl_E),
        .ALUSrc_D(ALUSrc_D),         .ALUSrc_E(ALUSrc_E),
        
        // Data
        .RD1_D(RD1_D),          .RD1_E(RD1_E),
        .RD2_D(RD2_D),          .RD2_E(RD2_E),
        .PC_D(PC_D),            .PC_E(PC_E),
        .ImmExt_D(ImmExt_D),    .ImmExt_E(ImmExt_E),
        .PCPlus4_D(PCPlus4_D),  .PCPlus4_E(PCPlus4_E),
        .Rd_D(Rd_D),            .Rd_E(Rd_E),
		.Rs1_D(Instr_D[19:15]), .Rs1_E(Rs1_E),
		.Rs2_D(Instr_D[24:20]), .Rs2_E(Rs2_E)
    );


    // ========================================================================
    // 3. EXECUTE STAGE
    // ========================================================================

    // For now (Naive Pipeline), SrcA is just RD1.
    assign SrcA_Forwarded = (ForwardA_E == 2'b10) ? ALUResult_M :
							(ForwardA_E == 2'b01) ? Result_W :
							RD1_E;
					
	assign SrcA_E = SrcA_Forwarded;
	
	assign SrcB_Forwarded = (ForwardB_E == 2'b10) ? ALUResult_M :
							(ForwardB_E == 2'b01) ? Result_W :
							RD2_E;
							
	assign SrcB_E = (ALUSrc_E)? ImmExt_E : SrcB_Forwarded;
					
	assign WriteData_E = SrcB_Forwarded;

    ALU u_alu (
        .SrcA(SrcA_E),
        .SrcB(SrcB_E),
        .ALUControl(ALUControl_E),
        .ALUResult(ALUResult_E),
        .Zero(Zero_E)
    );
    
    // Branch Target Calculator
    // FIXED: Added connections
    PCTarget u_pc_target (
        .PC(PC_E),
        .ImmExt(ImmExt_E),
        .PCTarget(PCTarget_E)
    );
    
    // Branch Decision Logic: (Branch & Zero) OR Jump
    assign PCSrc_E = (Branch_E & Zero_E) | Jump_E;

    // --- EX/MEM PIPELINE REGISTER ---
    Pipe_EX_MEM u_reg_ex_mem (
        .clk(cpu_clk),
        .rst_n(KEY[0]),
        
        // Control
        .RegWrite_E(RegWrite_E),   .RegWrite_M(RegWrite_M),
        .ResultSrc_E(ResultSrc_E), .ResultSrc_M(ResultSrc_M),
        .MemWrite_E(MemWrite_E),   .MemWrite_M(MemWrite_M),
        
        // Data
        .ALUResult_E(ALUResult_E), .ALUResult_M(ALUResult_M),
        .WriteData_E(WriteData_E), .WriteData_M(WriteData_M),
        .Rd_E(Rd_E),               .Rd_M(Rd_M),
        .PCPlus4_E(PCPlus4_E),     .PCPlus4_M(PCPlus4_M)
    );


    // ========================================================================
    // 4. MEMORY STAGE
    // ========================================================================
	
	// --- Internal Wires for UART ---
    wire [7:0] rx_byte;
    wire       rx_ready_pulse;
    wire       uart_tx_busy;
    
    // --- 1. Address Decoding (Magic Addresses) ---
    // Check the address calculated by the ALU in this stage
    wire is_uart_tx_addr = (ALUResult_M == 32'd84); // Write Char
    wire is_uart_rx_addr = (ALUResult_M == 32'd88); // Read Char
    wire is_status_addr  = (ALUResult_M == 32'd92); // Read Status

    // --- 2. UART Transmitter ---
    // Trigger sending ONLY if: 
    //   1. Logic wants to write to memory (MemWrite_M)
    //   2. The address is 84
    wire uart_start_tx = (MemWrite_M && is_uart_tx_addr);
	wire uart_tx_pin;
	assign ARDUINO_IO[0] = uart_tx_pin;
	
    UartTx u_debug_uart_tx (
        .clk(MAX10_CLK1_50), // Must use 50MHz
        .rst_n(KEY[0]),
        .start(uart_start_tx),
        .data(WriteData_M[7:0]), // Data comes from the Store value
        .tx(uart_tx_pin),        // Connect to the wire going to ARDUINO_IO[0]
        .ready(uart_tx_busy)
    );

    // --- 3. UART Receiver ---
    UartRx u_debug_uart_rx (
        .clk(MAX10_CLK1_50),
        .rst_n(KEY[0]),
        .rx(ARDUINO_IO[1]),
        .rx_data(rx_byte),
        .rx_ready(rx_ready_pulse)
    );

    // --- 4. Status Register (Sticky Bit) ---
    reg rx_status_bit;
    
    always @(posedge MAX10_CLK1_50 or negedge KEY[0]) begin
        if (!KEY[0]) begin
            rx_status_bit <= 1'b0;
        end else begin
            if (rx_ready_pulse) begin
                rx_status_bit <= 1'b1; // Set when new data arrives
            end 
            else if (is_uart_rx_addr) begin 
                rx_status_bit <= 1'b0; // Clear when CPU reads the data (Addr 88)
            end
        end
    end
	
    DataMemory u_dmem (
        .clk(cpu_clk),
        .WE(MemWrite_M && !is_uart_tx_addr),
        .A(ALUResult_M),
        .WD(WriteData_M),
        .RD(ram_read_data_M)
    );
	
	assign ReadData_M = (is_uart_rx_addr) ? {24'd0, rx_byte} : 
                        (is_status_addr)  ? {31'd0, rx_status_bit} : 
                        ram_read_data_M;

    // --- MEM/WB PIPELINE REGISTER ---
    Pipe_MEM_WB u_reg_mem_wb (
        .clk(cpu_clk),
        .rst_n(KEY[0]),
        
        // Control
        .RegWrite_M(RegWrite_M),   .RegWrite_W(RegWrite_W),
        .ResultSrc_M(ResultSrc_M), .ResultSrc_W(ResultSrc_W),
        
        // Data
        .ALUResult_M(ALUResult_M), .ALUResult_W(ALUResult_W),
        .ReadData_M(ReadData_M),   .ReadData_W(ReadData_W),
        .Rd_M(Rd_M),               .Rd_W(Rd_W),
        .PCPlus4_M(PCPlus4_M),     .PCPlus4_W(PCPlus4_W)
    );


    // ========================================================================
    // 5. WRITEBACK STAGE
    // ========================================================================

    // Result Mux (3-Way Mux for JAL/Load/ALU)
    // 00: ALU, 01: Memory, 10: PC+4
    assign Result_W = (ResultSrc_W[1]) ? PCPlus4_W : (ResultSrc_W[0]) ? ReadData_W : ALUResult_W;

//  // Debug: Show Program Counter (Fetch Stage) on LEDs
//  assign LEDR[7:0] = PC_F[7:0];
//	
//	// ---Control Flow Debugger---
//	// LED 0: Is it a Branch Instruction?
//	assign LEDR[0] = Branch_E;
//	
//	// LED 1: Is the Zero Flag active? (Are operands equal?)
//	assign LEDR[1] = Zero_E;
//	
//	// LED 2: The Final Decision (Take Branch?)
//	assign LEDR[2] = PCSrc_E;
//	
//	// LED 3: The Stall Signal (Are we stalling?)
//	assign LEDR[3] = StallF;
//	
//	// LED 4: The Flush Signal
//	assign LEDR[4] = FlushE;
//	
//	// LED 9-5: Keep PC to see movement
//	assign LEDR[9:5] = PC_F[6:2];
	
//	// --- DATA FLOW DEBUGGER ---
	// Show the lower 8 bits of the data being written back to registers.
//	assign LEDR[7:0] = Result_W[7:0];
//	
//	// Keep the UART Status bit on LED 9 so you know when data arrives
//	assign LEDR[9] = rx_status_bit;
//	
//	// Use LED 8 to show if we are writing to the UART TX address
//	// This tells us if the CPU *thinks* it is sending data
//	assign LEDR[8] = (ALUResult_M == 32'd84 && MemWrite_M);
	
//	// DEBUG UART TRANSMISSION
//	// LED 8: Is the CPU trying to write to Address 84?
//	assign LEDR[8] = (MemWrite_M && (ALUResult_M == 32'd84));
//	
	// LED 7:0 : show the data being written to Memory
	assign LEDR[7:0] = Result_W[7:0];
	
	assign LEDR[9] = uart_tx_busy;
	
endmodule
