// ============================================================================
//   Ver  :| Author					:| Mod. Date :| Changes Made:
//   V1.1 :| Alexandra Du			:| 06/01/2016:| Added Verilog file
// ============================================================================


//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

`define ENABLE_ADC_CLOCK
`define ENABLE_CLOCK1
`define ENABLE_CLOCK2
`define ENABLE_SDRAM
`define ENABLE_HEX0
`define ENABLE_HEX1
`define ENABLE_HEX2
`define ENABLE_HEX3
`define ENABLE_HEX4
`define ENABLE_HEX5
`define ENABLE_KEY
`define ENABLE_LED
`define ENABLE_SW
`define ENABLE_VGA
`define ENABLE_ACCELEROMETER
`define ENABLE_ARDUINO
`define ENABLE_GPIO

module DE10_LITE_Golden_Top(

	//////////// ADC CLOCK: 3.3-V LVTTL //////////
`ifdef ENABLE_ADC_CLOCK
	input 		          		ADC_CLK_10,
`endif
	//////////// CLOCK 1: 3.3-V LVTTL //////////
`ifdef ENABLE_CLOCK1
	input 		          		MAX10_CLK1_50,
`endif
	//////////// CLOCK 2: 3.3-V LVTTL //////////
`ifdef ENABLE_CLOCK2
	input 		          		MAX10_CLK2_50,
`endif

	//////////// SDRAM: 3.3-V LVTTL //////////
`ifdef ENABLE_SDRAM
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N,
`endif

	//////////// SEG7: 3.3-V LVTTL //////////
`ifdef ENABLE_HEX0
	output		     [7:0]		HEX0,
`endif
`ifdef ENABLE_HEX1
	output		     [7:0]		HEX1,
`endif
`ifdef ENABLE_HEX2
	output		     [7:0]		HEX2,
`endif
`ifdef ENABLE_HEX3
	output		     [7:0]		HEX3,
`endif
`ifdef ENABLE_HEX4
	output		     [7:0]		HEX4,
`endif
`ifdef ENABLE_HEX5
	output		     [7:0]		HEX5,
`endif

	//////////// KEY: 3.3 V SCHMITT TRIGGER //////////
`ifdef ENABLE_KEY
	input 		     [1:0]		KEY,
`endif

	//////////// LED: 3.3-V LVTTL //////////
`ifdef ENABLE_LED
	output		     [9:0]		LEDR,
`endif

	//////////// SW: 3.3-V LVTTL //////////
`ifdef ENABLE_SW
	input 		     [9:0]		SW,
`endif

	//////////// VGA: 3.3-V LVTTL //////////
`ifdef ENABLE_VGA
	output		     [3:0]		VGA_B,
	output		     [3:0]		VGA_G,
	output		          		VGA_HS,
	output		     [3:0]		VGA_R,
	output		          		VGA_VS,
`endif

	//////////// Accelerometer: 3.3-V LVTTL //////////
`ifdef ENABLE_ACCELEROMETER
	output		          		GSENSOR_CS_N,
	input 		     [2:1]		GSENSOR_INT,
	output		          		GSENSOR_SCLK,
	inout 		          		GSENSOR_SDI,
	inout 		          		GSENSOR_SDO,
`endif

	//////////// Arduino: 3.3-V LVTTL //////////
`ifdef ENABLE_ARDUINO
	inout 		    [15:0]		ARDUINO_IO,
	inout 		          		ARDUINO_RESET_N,
`endif

	//////////// GPIO, GPIO connect to GPIO Default: 3.3-V LVTTL //////////
`ifdef ENABLE_GPIO
	inout 		    [35:0]		GPIO
`endif
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
reg start_transaction;
reg is_read_op;
wire i2c_is_busy;
wire transaction_done;
wire [6:0] target_addr;
reg [7:0] target_reg;

reg rd_en;
reg wr_en;
wire [15:0] rd_data;
reg [15:0] wr_data;
wire full, empty;

wire [7:0] data_read;
reg [7:0] data_to_write;

reg [7:0] Ldata_reg;

reg [15:0] x_data, y_data, z_data;
//=======================================================
//  Structural coding
//=======================================================

assign GSENSOR_CS_N = 1'b1; // Set it HIGH to select the I2C mode
assign GSENSOR_SDO = 1'b0;
assign target_addr = 7'h53; // Address for G-Sensor(ADXL345) when GSENSOR_SDO is LOW

//assign GSENSOR_SDO = 1'b1;
//assign target_addr = 7'h1D; // Address for G-Sensor(ADXL345) when GSENSOR_SDO is HIGH

reg [3:0] state, next_state;
localparam IDLE = 4'd0;
localparam BOOT_UP1 = 4'd1;
localparam BOOT_UP2 = 4'd2;
localparam X_LDATA = 4'd3;
localparam X_UDATA = 4'd4;
localparam Y_LDATA = 4'd5;
localparam Y_UDATA = 4'd6;
localparam Z_LDATA = 4'd7;
localparam Z_UDATA = 4'd8;

always @(posedge MAX10_CLK1_50 or negedge KEY[0])begin
	if(!KEY[0])begin
		state <= IDLE;
	end else begin
		state <= next_state;
	end
end

always @(*)begin
	case(state)
		IDLE:begin
			if(SW[0]) next_state = BOOT_UP1; // SW[0] UP to start
			else next_state = IDLE;
		end
		
		BOOT_UP1:begin
			if(transaction_done) next_state = BOOT_UP2;
			else next_state = BOOT_UP1;
		end
		
		BOOT_UP2:begin
			if(transaction_done) next_state = X_LDATA;
			else next_state = BOOT_UP2;
		end
		
		X_LDATA:begin
			if(transaction_done) next_state = X_UDATA;
			else next_state = X_LDATA;
		end
		
		X_UDATA:begin
			if(transaction_done) next_state = Y_LDATA;
			else next_state = X_UDATA;
		end
		
		Y_LDATA:begin
			if(transaction_done) next_state = Y_UDATA;
			else next_state = Y_LDATA;
		end
		
		Y_UDATA:begin
			if(transaction_done) next_state = Z_LDATA;
			else next_state = Y_UDATA;
		end
		
		Z_LDATA:begin
			if(transaction_done) next_state = Z_UDATA;
			else next_state = Z_LDATA;
		end
		
		Z_UDATA:begin
			if(transaction_done) next_state = X_LDATA;
			else next_state = Z_UDATA;
		end
		
		default: next_state = IDLE;
	endcase
end

always @(posedge MAX10_CLK1_50)begin
	// Set the default value, and make them as a pulse
	start_transaction <= 1'b0;
	wr_en <= 1'b0;
	case(state)
		IDLE: start_transaction <= 1'b0;
		
		BOOT_UP1: begin
			if(!i2c_is_busy) start_transaction <= 1'b1;
			target_reg <= 8'h31;
			data_to_write <= 8'h0B;
			is_read_op <= 1'b0; // Write
		end
		
		BOOT_UP2:begin
			if(!i2c_is_busy) start_transaction <= 1'b1;
			target_reg <= 8'h2D;
			data_to_write <= 8'h08;
			is_read_op <= 1'b0; 
		end
		
		X_LDATA:begin
			if(!i2c_is_busy) start_transaction <= 1'b1;
			target_reg <= 8'h32;
			is_read_op <= 1'b1; // Read
			if(transaction_done) Ldata_reg <= data_read;
		end
		
		X_UDATA:begin
			if(!i2c_is_busy) start_transaction <= 1'b1;
			target_reg <= 8'h33;
			is_read_op <= 1'b1; // Read
			if(transaction_done && !full)begin
				wr_data <= {data_read, Ldata_reg};
				wr_en <= 1'b1;
			end
		end
		
		Y_LDATA:begin
			if(!i2c_is_busy) start_transaction <= 1'b1;
			target_reg <= 8'h34;
			is_read_op <= 1'b1; // Read
			if(transaction_done) Ldata_reg <= data_read;
		end
		
		Y_UDATA:begin
			if(!i2c_is_busy) start_transaction <= 1'b1;
			target_reg <= 8'h35;
			is_read_op <= 1'b1; // Read
			if(transaction_done && !full)begin
				wr_data <= {data_read, Ldata_reg};
				wr_en <= 1'b1;
			end
		end
		
		Z_LDATA:begin
			if(!i2c_is_busy) start_transaction <= 1'b1;
			target_reg <= 8'h36;
			is_read_op <= 1'b1; // Read
			if(transaction_done) Ldata_reg <= data_read;
		end
		
		Z_UDATA:begin
			if(!i2c_is_busy) start_transaction <= 1'b1;
			target_reg <= 8'h37;
			is_read_op <= 1'b1; // Read
			if(transaction_done && !full)begin
				wr_data <= {data_read, Ldata_reg};
				wr_en <= 1'b1;
			end
		end
	endcase
end

I2CController i2c_worker (
    // System 
    .clk(MAX10_CLK1_50), 
    .rst_n(KEY[0]),

    // --- CONTROL FLOW (The Handshake) ---
    .enable(start_transaction), 
    .rw(is_read_op),
    .busy(i2c_is_busy),         
    .done(transaction_done),    

    // --- DATA FLOW (The Payload) ---
    .device_addr(target_addr),  
    .reg_addr(target_reg),      
    .data_in(data_to_write),    
    .data_out(data_read),       

    // --- PHYSICAL BUS (To the outside world) ---
    .SCL(GSENSOR_SCLK),         // Connected to physical DE10-Lite pin
    .SDA(GSENSOR_SDI)           // Connected to physical DE10-Lite pin
);

FIFO data_fifo(
	.clk(MAX10_CLK1_50), 
    .rst_n(KEY[0]),
	
	.rd_en(rd_en),
	.wr_en(wr_en),
	.full(full),
	.empty(empty),
	
	.wr_data(wr_data),
	.rd_data(rd_data)
);

reg [1:0] data_counter; // For X, Y, Z data
localparam COUNT_TARGET = 2;

reg [1:0] rstate, rnext_state;
localparam WAIT_EMPTY = 2'd0;
localparam WAIT_RAM = 2'd1;
localparam SAVE_DATA = 2'd2;

always @(posedge MAX10_CLK1_50 or negedge KEY[0])begin
	if(!KEY[0])begin
		rstate <= WAIT_EMPTY;
	end else begin
		rstate <= rnext_state;
	end
end

always @(*)begin
	case(rstate)
		WAIT_EMPTY:begin
			if(!empty) rnext_state = WAIT_RAM;
			else rnext_state = WAIT_EMPTY;
		end
		
		WAIT_RAM:begin
			rnext_state = SAVE_DATA;
		end
		
		SAVE_DATA:begin
			rnext_state = WAIT_EMPTY;
		end
	endcase
end


always @(posedge MAX10_CLK1_50 or negedge KEY[0])begin
	if(!KEY[0])begin
		data_counter <= 2'd0;
	end else begin
		rd_en <= 1'b0;
		case(rstate)
			WAIT_EMPTY: if(!empty) rd_en <= 1'b1;
			SAVE_DATA:begin
				if(data_counter == 0) x_data <= rd_data;
				else if(data_counter == 1) y_data <= rd_data;
				else if(data_counter == 2) z_data <= rd_data;
				if(data_counter < COUNT_TARGET) data_counter <= data_counter + 1'b1;
				else data_counter <= 2'd0;
			end
		endcase
	end
end
// x_data, y_data, and z_data from the FIFO!

	// Z-Axis
	Axis_Display_Driver z_axis_disp (
		.axis_data(z_data),
		.led_sign(LEDR[0]),
		.hex_int(HEX1[6:0]),
		.hex_frac(HEX0[6:0])
	);
	
	// Y-Axis
	Axis_Display_Driver y_axis_disp (
		.axis_data(y_data),
		.led_sign(LEDR[4]),
		.hex_int(HEX3[6:0]),
		.hex_frac(HEX2[6:0])
	);
	
	// X-Axis
	Axis_Display_Driver x_axis_disp (
		.axis_data(x_data),
		.led_sign(LEDR[8]),
		.hex_int(HEX5[6:0]),
		.hex_frac(HEX4[6:0])
	);
	// Turn on the decimal points for the integer digits!
	assign HEX1[7] = 1'b0; 
	assign HEX3[7] = 1'b0;
	assign HEX5[7] = 1'b0;
	
	// Turn off the decimal points for the fraction digits
	assign HEX0[7] = 1'b1;
	assign HEX2[7] = 1'b1;
	assign HEX4[7] = 1'b1;
endmodule
