// ============================================================================
//   Ver  :| Author					:| Mod. Date :| Changes Made:
//   V1.1 :| Alexandra Du			:| 06/01/2016:| Added Verilog file
// ============================================================================


//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

`define ENABLE_ADC_CLOCK
`define ENABLE_CLOCK1
`define ENABLE_CLOCK2
`define ENABLE_SDRAM
`define ENABLE_HEX0
`define ENABLE_HEX1
`define ENABLE_HEX2
`define ENABLE_HEX3
`define ENABLE_HEX4
`define ENABLE_HEX5
`define ENABLE_KEY
`define ENABLE_LED
`define ENABLE_SW
`define ENABLE_VGA
`define ENABLE_ACCELEROMETER
`define ENABLE_ARDUINO
`define ENABLE_GPIO

module DE10_LITE_Golden_Top(

	//////////// ADC CLOCK: 3.3-V LVTTL //////////
`ifdef ENABLE_ADC_CLOCK
	input 		          		ADC_CLK_10,
`endif
	//////////// CLOCK 1: 3.3-V LVTTL //////////
`ifdef ENABLE_CLOCK1
	input 		          		MAX10_CLK1_50,
`endif
	//////////// CLOCK 2: 3.3-V LVTTL //////////
`ifdef ENABLE_CLOCK2
	input 		          		MAX10_CLK2_50,
`endif

	//////////// SDRAM: 3.3-V LVTTL //////////
`ifdef ENABLE_SDRAM
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N,
`endif

	//////////// SEG7: 3.3-V LVTTL //////////
`ifdef ENABLE_HEX0
	output		     [7:0]		HEX0,
`endif
`ifdef ENABLE_HEX1
	output		     [7:0]		HEX1,
`endif
`ifdef ENABLE_HEX2
	output		     [7:0]		HEX2,
`endif
`ifdef ENABLE_HEX3
	output		     [7:0]		HEX3,
`endif
`ifdef ENABLE_HEX4
	output		     [7:0]		HEX4,
`endif
`ifdef ENABLE_HEX5
	output		     [7:0]		HEX5,
`endif

	//////////// KEY: 3.3 V SCHMITT TRIGGER //////////
`ifdef ENABLE_KEY
	input 		     [1:0]		KEY,
`endif

	//////////// LED: 3.3-V LVTTL //////////
`ifdef ENABLE_LED
	output		     [9:0]		LEDR,
`endif

	//////////// SW: 3.3-V LVTTL //////////
`ifdef ENABLE_SW
	input 		     [9:0]		SW,
`endif

	//////////// VGA: 3.3-V LVTTL //////////
`ifdef ENABLE_VGA
	output		     [3:0]		VGA_B,
	output		     [3:0]		VGA_G,
	output		          		VGA_HS,
	output		     [3:0]		VGA_R,
	output		          		VGA_VS,
`endif

	//////////// Accelerometer: 3.3-V LVTTL //////////
`ifdef ENABLE_ACCELEROMETER
	output		          		GSENSOR_CS_N,
	input 		     [2:1]		GSENSOR_INT,
	output		          		GSENSOR_SCLK,
	inout 		          		GSENSOR_SDI,
	inout 		          		GSENSOR_SDO,
`endif

	//////////// Arduino: 3.3-V LVTTL //////////
`ifdef ENABLE_ARDUINO
	inout 		    [15:0]		ARDUINO_IO,
	inout 		          		ARDUINO_RESET_N,
`endif

	//////////// GPIO, GPIO connect to GPIO Default: 3.3-V LVTTL //////////
`ifdef ENABLE_GPIO
	inout 		    [35:0]		GPIO
`endif
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
wire [31:0] PC;
wire [31:0] PCNext;
wire [31:0] Instr;
wire Zero;
wire PCSrc;
wire ResultSrc;
wire MemWrite;
wire [2:0] ALUControl;
wire ALUSrc;
wire [1:0] ImmSrc;
wire RegWrite;
wire [31:0] RD1;
wire [31:0] WriteData;
wire [31:0] ImmExt;
wire [31:0] PCTarget;
wire [31:0] ReadData;
wire [31:0] Result;
wire [31:0] SrcB;
wire [31:0] PCPlus4;
wire [31:0] ALUResult;
wire cpu_clk = KEY[1];


wire [31:0] ram_read_data;
// 2. The Mux: Decide what the CPU reads
// If address is 88, give it the UART byte (padded with 0s).
// Otherwise, give it the RAM data.
assign ReadData = (is_rx_addr)     ? {24'd0, rx_byte} : 
                      (is_status_addr) ? {31'd0, rx_status_bit} : 
                      ram_read_data;

//=======================================================
//  Structural coding
//=======================================================
ControlUnit u_control (
    .Opcode(Instr[6:0]),
    .Funct3(Instr[14:12]),
    .Funct7b5(Instr[30]),
    .Zero(Zero),
    .PCSrc(PCSrc),
    .ResultSrc(ResultSrc),
    .MemWrite(MemWrite),
    .ALUSrc(ALUSrc),
    .ImmSrc(ImmSrc),
    .RegWrite(RegWrite),
    .ALUControl(ALUControl)
);

ProgramCounter u_pc (
    .clk(MAX10_CLK1_50),
    .rst_n(KEY[0]),
    .PCNext(PCNext),
    .PC(PC)
);

PCAdder u_pc_adder (
    .PC(PC),
    .PCPlus4(PCPlus4)
);

InstructionMemory u_imem (
    .A(PC),
    .RD(Instr)
);

RegisterFile u_reg_file (
    .clk(MAX10_CLK1_50),
    .WE3(RegWrite),
    .A1(Instr[19:15]),
    .A2(Instr[24:20]),
    .A3(Instr[11:7]),
    .WD3(Result),
    .RD1(RD1),
    .RD2(WriteData)
);

Extend u_extend (
    .Instr(Instr[31:7]),
    .ImmSrc(ImmSrc),
    .ImmExt(ImmExt)
);

ALU u_alu (
    .SrcA(RD1),
    .SrcB(SrcB),
    .ALUControl(ALUControl),
    .ALUResult(ALUResult),
    .Zero(Zero)
);

PCTarget u_pc_target (
    .PC(PC),
    .ImmExt(ImmExt),
    .PCTarget(PCTarget)
);

DataMemory u_dmem (
    .clk(MAX10_CLK1_50),
    .WE(real_mem_write),
    .A(ALUResult),
    .WD(WriteData),
    .RD(ram_read_data)
);

// MUX for PC (PCMux)
Mux2 u_pc_mux (
    .d0(PCPlus4),    // Input 0
    .d1(PCTarget),    // Input 1
    .s(PCSrc),     // Select Signal
    .y(PCNext)      // Output
);

// MUX for ALU Source B (SrcBMux)
Mux2 u_srcb_mux (
    .d0(WriteData),
    .d1(ImmExt),
    .s(ALUSrc),
    .y(SrcB)
);

// MUX for Result (ResultMux)
Mux2 u_result_mux (
    .d0(ALUResult),
    .d1(ReadData),
    .s(ResultSrc),
    .y(Result)
);
	// =======================================================
    // STATUS REGISTER LOGIC (Sticky Bit)
    // =======================================================
    reg rx_status_bit;
    
    // Address 92 (0x5C) is the Status Register
    wire is_status_addr;
    assign is_status_addr = (ALUResult == 32'd92);

    always @(posedge MAX10_CLK1_50 or negedge KEY[0]) begin
        if (!KEY[0]) begin
            rx_status_bit <= 1'b0;
        end else begin
            if (rx_ready_pulse) begin
                rx_status_bit <= 1'b1; // Set when UART has new data
            end else if (is_rx_addr) begin 
                rx_status_bit <= 1'b0; // Clear when CPU reads the data (Addr 88)
            end
        end
    end
// 1. Define a Magic Address (e.g., 84)
wire is_uart_address;
assign is_uart_address = (ALUResult == 32'd84);

// 2. Intercept MemWrite
// Only write to real RAM if it is NOT the UART address
wire real_mem_write;
assign real_mem_write = MemWrite && !is_uart_address;

// 3. Trigger UART
// Start sending if MemWrite is TRUE and Address IS UART
wire uart_start;
assign uart_start = MemWrite && is_uart_address;

// 4. Instantiate UART TX
wire tx_ready;

UartTx u_uart_tx (
	.clk(MAX10_CLK1_50),
	.rst_n(KEY[0]),
	.start(uart_start),
	.data(WriteData[7:0]), // Send the bottom 8 bits of the register
	.tx(ARDUINO_IO[0]),
	.ready(tx_ready)
);
// UART RX Signals
wire [7:0] rx_byte;
wire       rx_ready_pulse; // Pulse from the UART module
wire       is_rx_addr;

// Define the "Magic Address" for Reading (88)
assign is_rx_addr = (ALUResult == 32'd88);

UartRx u_uart_rx (
	.clk(MAX10_CLK1_50),
	.rst_n(KEY[0]),
	.rx_data(rx_byte), 
	.rx(ARDUINO_IO[1]),
	.rx_ready(rx_ready_pulse)
);
// assign LEDR[7:0] = PC[7:0];
// New: Debug RX Data
assign LEDR[7:0] = rx_byte; // Show the byte sitting in the UART RX buffer
assign LEDR[9]   = rx_ready_pulse; // Flash when a byte arrives
endmodule
